# Generated by Django 5.1.4 on 2025-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_titlebanner2_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlebanner',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
