# Generated by Django 5.2.4 on 2025-08-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_chooseus_homebanner_lastestblog_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
    ]
