# Generated by Django 5.2.4 on 2025-08-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_footersection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastestblog',
            old_name='commenttext1',
            new_name='commenttext',
        ),
        migrations.RenameField(
            model_name='lastestblog',
            old_name='commenttitle1',
            new_name='commenttitle',
        ),
        migrations.RenameField(
            model_name='lastestblog',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lastestblog',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lastestblog',
            old_name='commenttitle2',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='commenttext2',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='commenttext3',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='commenttitle3',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='date3',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='user3',
        ),
    ]
