# Generated by Django 5.2.4 on 2025-08-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_commenttext1_lastestblog_commenttext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastestblog',
            name='maintext',
        ),
        migrations.RemoveField(
            model_name='lastestblog',
            name='maintitle',
        ),
    ]
