# Generated by Django 5.2.4 on 2025-08-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_titlebanner2_menuid_remove_menudetail2_menuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub2menu',
            old_name='menuID',
            new_name='menuId',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='menuID',
            new_name='menuId',
        ),
    ]
