# Generated by Django 5.2.4 on 2025-08-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_rename_menuid_sub2menu_menuid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastestBlog',
            new_name='Blog',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='shop.blog')),
            ],
        ),
    ]
