# Generated by Django 5.2.4 on 2025-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_lastestblog_blog_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
