# Generated by Django 5.2.3 on 2025-07-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='laste_on_sale',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
