# Generated by Django 5.2.3 on 2025-07-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_car_laste_on_sale_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='laste_on_sale',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
