# Generated by Django 5.1.4 on 2025-07-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_menu_remove_feature_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
