# Generated by Django 5.1.4 on 2025-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_menudetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudetail',
            name='MenuID',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuDetail',
        ),
    ]
