# Generated by Django 5.1.4 on 2025-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_menu_menu2_menudetail_menudetail2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
