# Generated by Django 5.1.4 on 2025-07-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_titlebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlebanner',
            name='MenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.menu'),
        ),
    ]
