# Generated by Django 5.1.4 on 2025-07-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_titlebanner_menuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBanner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('MenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.menu2')),
            ],
        ),
    ]
