# Generated by Django 5.2.4 on 2025-07-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_titlebanner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('maintext', models.TextField(blank=True, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='choose_us/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_banners/')),
                ('title', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastestBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=200, null=True)),
                ('maintext', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='latest_blogs/')),
                ('user1', models.CharField(max_length=200, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('commenttitle1', models.CharField(max_length=200, null=True)),
                ('commenttext1', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='latest_blogs/')),
                ('user2', models.CharField(max_length=200, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('commenttitle2', models.CharField(max_length=200, null=True)),
                ('commenttext2', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='latest_blogs/')),
                ('user3', models.CharField(max_length=200, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('commenttitle3', models.CharField(max_length=200, null=True)),
                ('commenttext3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=200, null=True)),
                ('maintext', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title1', models.CharField(max_length=200, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title2', models.CharField(max_length=200, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title3', models.CharField(max_length=200, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title4', models.CharField(max_length=200, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='footersection',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
        migrations.AddField(
            model_name='footersection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
    ]
