# Generated by Django 5.2.4 on 2025-08-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_lastestblog_maintext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlebanner2',
            name='MenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.menu'),
        ),
        migrations.RemoveField(
            model_name='menudetail2',
            name='MenuID',
        ),
        migrations.RemoveField(
            model_name='menudetail',
            name='MenuID',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='MenuNameEN',
            new_name='menuName',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='OrderBy',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('menuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='shop.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Sub2Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('menuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.submenu')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu2',
        ),
        migrations.DeleteModel(
            name='MenuDetail2',
        ),
        migrations.DeleteModel(
            name='MenuDetail',
        ),
    ]
