# Generated by Django 5.1.4 on 2025-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_blogdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
