# Generated by Django 5.1.4 on 2025-08-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_blogdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('user', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('commenttitle', models.CharField(max_length=200, null=True)),
                ('commenttext', models.TextField(blank=True, null=True)),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
