# Generated by Django 5.1.4 on 2025-08-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_blogdetails_delete_blogdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetails',
        ),
    ]
