# Generated by Django 5.1.4 on 2025-08-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_cardetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardetailimages', to='shop.car')),
            ],
        ),
    ]
