# Generated by Django 5.1.4 on 2025-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_cardetailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
