# Generated by Django 5.1.4 on 2025-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_cardetails_text_cardetails_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='stock',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
