# Generated by Django 5.1.4 on 2025-08-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_cardetails_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='originalPrice',
        ),
    ]
